# Aprendizagem supervisionada: Classificação

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "iframe"

In [5]:
df = pd.read_csv('heart_tratado.csv', sep=';', encoding = 'utf-8')

In [6]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0

In [7]:
df.shape

(917, 12)

# Transformando as variaveis vategórivas nominais em variaveis categóricas ordinais

In [9]:
df2 = pd.DataFrame.copy(df)

In [11]:
df2['Sex'].replace({'M':0, 'F':1}, inplace = True)
df2['ChestPainType'].replace({'TA':0, 'ATA':1, 'NAP':2, 'ASY':3}, inplace = True)
df2['RestingECG'].replace({'Normal':0, 'ST':1, 'LVH':2}, inplace = True)
df2['ExerciseAngina'].replace({'N':0, 'Y':1, 'NAP':2}, inplace = True)
df2['ST_Slope'].replace({'Up':0, 'Flat':1, 'Down':2}, inplace = True)

/tmp/ipykernel_7622/531397148.py:4: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_7622/531397148.py:4: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/tmp/ipykernel_7622/531397148.py:5: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_7622/531397148.py:5: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [12]:
df2.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,1,140,289.0,0,0,172,0,0.0,0,0
1,49,1,2,160,180.0,0,0,156,0,1.0,1,1
2,37,0,1,130,283.0,0,1,98,0,0.0,0,0
3,48,1,3,138,214.0,0,0,108,1,1.5,1,1
4,54,0,2,150,195.0,0,0,122,0,0.0,0,0

In [13]:
df2.dtypes

Age                 int64
Sex                 int64
ChestPainType       int64
RestingBP           int64
Cholesterol       float64
FastingBS           int64
RestingECG          int64
MaxHR               int64
ExerciseAngina      int64
Oldpeak           float64
ST_Slope            int64
HeartDisease        int64
dtype: object

In [14]:
df2.shape

(917, 12)


## 📘 LEGENDA

- **Age** = idade (anos)  
- **Sex** = sexo (0 = M; 1 = F)  

- **Chest Pain Type** = tipo de dor no peito  
  - 0 = TA (angina típica)  
  - 1 = ATA (angina atípica)  
  - 2 = NAP (dor não anginosa)  
  - 3 = ASY (assintomático)  

- **Resting BP** = pressão sanguínea em repouso (mmHg)  
- **Cholesterol** = colesterol sérico (mg/dl)  

- **Fasting BS** = açúcar no sangue em jejum (mg/dl)  
  - 0 = Fasting BS < 120 mg/dl (não diabético)  
  - 1 = Fasting BS ≥ 120 mg/dl (diabético)  

- **Resting ECG** = eletrocardiograma em repouso  
  - 0 = Normal  
  - 1 = ST (anormalidade da onda ST-T)  
  - 2 = LVH (hipertrofia ventricular esquerda)  

- **Max HR** = frequência cardíaca máxima  

- **Exercise Angina** = angina induzida por exercício  
  - 0 = Não  
  - 1 = Sim  

- **Old Peak** = depressão do ST induzida por exercício em relação ao repouso  

- **ST_Slope** = inclinação do segmento ST  
  - 0 = UP  
  - 1 = Flat  
  - 2 = Down  

- **Heart Disease** = doença cardíaca  
  - 0 = Não possui doença cardíaca  
  - 1 = Possui doença cardíaca